alias cp='cp -i'
alias ectool='~/code/EmbeddedController/build/hx20/util/ectool'
alias g='git'
alias gb='git branch'
alias gc='git commit'
alias gcan='git commit --amend --no-edit --date now'
alias gco='git checkout'
alias gd='git diff'
alias gf='git fetch'
alias gl='git pull'
alias glog='git log --oneline --graph'
alias gloga='git log --oneline --graph --all'
alias gp='git push'
alias gst='git status'
alias l.='ls -d .* --color=auto'
alias ll='ls -l --color=auto'
alias ls='ls --color=auto'
alias mv='mv -i'
alias rm='rm -i'
